pipeline {
  agent {
    dockerfile true
    label 'slave'
  }
  
  stages {
    stage('hello'){
      steps {
        sh 'java -version'
        sh 'node --version'
        echo "Get working directory"
        sh 'pwd'
      }
    }
  }
}
